spring.application.name=olx-backend

# --- MySQL ---
spring.datasource.url=jdbc:mysql://localhost:3306/demoo?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=manager
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Flyway disabled (your earlier error with MySQL 8.4) ---
spring.flyway.enabled=false

# --- JWT ---
jwt.secret=Fq8r6r8j0v3pK1qS7xN2yV4wM8bC5tE0uR9aZ1dH3fL6pQ7sX4wT9q
jwt.expiration-hours=10
